### ISSUE TITLE
Implementing the API Call

### ISSUE THREAD

**Issue by umututku03** [CSC207-fiveguys/music-java-app#11]
**Description**
Currently, we have successfully completed the login and signup use-cases, pivotal components for our user-centric music application. However, a critical element remains outstanding—the integration with our database. It's essential to note that our reliance on the Spotify API for music, artists, and related data poses a challenge. The absence of the API implementation leaves us vulnerable, hindering progress on other key use-cases like playlist creation and adding songs.

**Work Delegation**
Bryan and Hussain will collaborate to address this issue.

**To-do**
[ ] Implement the Spotify API Call (For your reference, here is detailed guide https://developer.spotify.com/documentation/web-api/tutorials/getting-started).
[ ] Adhere meticulously to Clean Architecture and SOLID Principles to ensure a robust and maintainable codebase.
[ ] Pay close attention to naming conventions, follow Java rules, and consider code reformatting for consistency.
[ ] Explore the application of Design Patterns covered in the course, incorporating them where possible to enhance code organization and readability.
[ ] Be sure to document your work while working through the code.
[ ] Create comprehensive test cases to validate the functionality and reliability of the implemented Spotify API integration.

**Comment by HussainE4** [comment]
Linked the issue to the branch in which Brian and I are working on the issue
